# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Language.create(name: 'ABAP')
Language.create(name: 'AGS Script')
Language.create(name: 'AMPL')
Language.create(name: 'ANTLR')
Language.create(name: 'API Blueprint')
Language.create(name: 'APL')
Language.create(name: 'ASP')
Language.create(name: 'ATS')
Language.create(name: 'ActionScript')
Language.create(name: 'Ada')
Language.create(name: 'Agda')
Language.create(name: 'Alloy')
Language.create(name: 'Ant Build System')
Language.create(name: 'ApacheConf')
Language.create(name: 'Apex')
Language.create(name: 'AppleScript')
Language.create(name: 'Arc')
Language.create(name: 'Arduino')
Language.create(name: 'AsciiDoc')
Language.create(name: 'AspectJ')
Language.create(name: 'Assembly')
Language.create(name: 'Augeas')
Language.create(name: 'AutoHotkey')
Language.create(name: 'AutoIt')
Language.create(name: 'Awk')
Language.create(name: 'Batchfile')
Language.create(name: 'Befunge')
Language.create(name: 'Bison')
Language.create(name: 'BitBake')
Language.create(name: 'BlitzBasic')
Language.create(name: 'BlitzMax')
Language.create(name: 'Bluespec')
Language.create(name: 'Boo')
Language.create(name: 'Brainfuck')
Language.create(name: 'Brightscript')
Language.create(name: 'Bro')
Language.create(name: 'C')
Language.create(name: 'C#')
Language.create(name: 'C++')
Language.create(name: 'C-ObjDump')
Language.create(name: 'C2hs Haskell')
Language.create(name: 'CLIPS')
Language.create(name: 'CMake')
Language.create(name: 'COBOL')
Language.create(name: 'CSS')
Language.create(name: "Cap'n Proto")
Language.create(name: 'CartoCSS')
Language.create(name: 'Ceylon')
Language.create(name: 'Chapel')
Language.create(name: 'Charity')
Language.create(name: 'ChucK')
Language.create(name: 'Cirru')
Language.create(name: 'Clarion')
Language.create(name: 'Clean')
Language.create(name: 'Click')
Language.create(name: 'Clojure')
Language.create(name: 'CoffeeScript')
Language.create(name: 'ColdFusion')
Language.create(name: 'ColdFusion CFC')
Language.create(name: 'Common Lisp')
Language.create(name: 'Component Pascal')
Language.create(name: 'Cool')
Language.create(name: 'Coq')
Language.create(name: 'Cpp-ObjDump')
Language.create(name: 'Creole')
Language.create(name: 'Crystal')
Language.create(name: 'Cucumber')
Language.create(name: 'Cuda')
Language.create(name: 'Cycript')
Language.create(name: 'Cython')
Language.create(name: 'D')
Language.create(name: 'D-ObjDump')
Language.create(name: 'DIGITAL Command Language')
Language.create(name: 'DM')
Language.create(name: 'DNS Zone')
Language.create(name: 'DTrace')
Language.create(name: 'Darcs Patch')
Language.create(name: 'Dart')
Language.create(name: 'Diff')
Language.create(name: 'Dockerfile')
Language.create(name: 'Dogescript')
Language.create(name: 'Dylan')
Language.create(name: 'E')
Language.create(name: 'ECL')
Language.create(name: 'ECLiPSe')
Language.create(name: 'Eagle')
Language.create(name: 'Ecere Projects')
Language.create(name: 'Eiffel')
Language.create(name: 'Elixir')
Language.create(name: 'Elm')
Language.create(name: 'Emacs Lisp')
Language.create(name: 'EmberScript')
Language.create(name: 'Erlang')
Language.create(name: 'F#')
Language.create(name: 'FLUX')
Language.create(name: 'FORTRAN')
Language.create(name: 'Factor')
Language.create(name: 'Fancy')
Language.create(name: 'Fantom')
Language.create(name: 'Filterscript')
Language.create(name: 'Formatted')
Language.create(name: 'Forth')
Language.create(name: 'FreeMarker')
Language.create(name: 'Frege')
Language.create(name: 'G-code')
Language.create(name: 'GAMS')
Language.create(name: 'GAP')
Language.create(name: 'GAS')
Language.create(name: 'GDScript')
Language.create(name: 'GLSL')
Language.create(name: 'Game Maker Language')
Language.create(name: 'Genshi')
Language.create(name: 'Gentoo Ebuild')
Language.create(name: 'Gentoo Eclass')
Language.create(name: 'Gettext Catalog')
Language.create(name: 'Glyph')
Language.create(name: 'Gnuplot')
Language.create(name: 'Go')
Language.create(name: 'Golo')
Language.create(name: 'Gosu')
Language.create(name: 'Grace')
Language.create(name: 'Gradle')
Language.create(name: 'Grammatical Framework')
Language.create(name: 'Graph Modeling Language')
Language.create(name: 'Graphviz (DOT)')
Language.create(name: 'Groff')
Language.create(name: 'Groovy')
Language.create(name: 'Groovy Server Pages')
Language.create(name: 'HCL')
Language.create(name: 'HTML')
Language.create(name: 'HTML+Django')
Language.create(name: 'HTML+EEX')
Language.create(name: 'HTML+ERB')
Language.create(name: 'HTML+PHP')
Language.create(name: 'HTTP')
Language.create(name: 'Hack')
Language.create(name: 'Haml')
Language.create(name: 'Handlebars')
Language.create(name: 'Harbour')
Language.create(name: 'Haskell')
Language.create(name: 'Haxe')
Language.create(name: 'Hy')
Language.create(name: 'HyPhy')
Language.create(name: 'IDL')
Language.create(name: 'IGOR Pro')
Language.create(name: 'INI')
Language.create(name: 'IRC log')
Language.create(name: 'Idris')
Language.create(name: 'Inform 7')
Language.create(name: 'Inno Setup')
Language.create(name: 'Io')
Language.create(name: 'Ioke')
Language.create(name: 'Isabelle')
Language.create(name: 'Isabelle ROOT')
Language.create(name: 'J')
Language.create(name: 'JFlex')
Language.create(name: 'JSON')
Language.create(name: 'JSON5')
Language.create(name: 'JSONLD')
Language.create(name: 'JSONiq')
Language.create(name: 'JSX')
Language.create(name: 'Jade')
Language.create(name: 'Jasmin')
Language.create(name: 'Java')
Language.create(name: 'Java Server Pages')
Language.create(name: 'JavaScript')
Language.create(name: 'Julia')
Language.create(name: 'Jupyter Notebook')
Language.create(name: 'KRL')
Language.create(name: 'KiCad')
Language.create(name: 'Kit')
Language.create(name: 'Kotlin')
Language.create(name: 'LFE')
Language.create(name: 'LLVM')
Language.create(name: 'LOLCODE')
Language.create(name: 'LSL')
Language.create(name: 'LabVIEW')
Language.create(name: 'Lasso')
Language.create(name: 'Latte')
Language.create(name: 'Lean')
Language.create(name: 'Less')
Language.create(name: 'Lex')
Language.create(name: 'LilyPond')
Language.create(name: 'Limbo')
Language.create(name: 'Linker Script')
Language.create(name: 'Linux Kernel Module')
Language.create(name: 'Liquid')
Language.create(name: 'Literate Agda')
Language.create(name: 'Literate CoffeeScript')
Language.create(name: 'Literate Haskell')
Language.create(name: 'LiveScript')
Language.create(name: 'Logos')
Language.create(name: 'Logtalk')
Language.create(name: 'LookML')
Language.create(name: 'LoomScript')
Language.create(name: 'Lua')
Language.create(name: 'M')
Language.create(name: 'MAXScript')
Language.create(name: 'MTML')
Language.create(name: 'MUF')
Language.create(name: 'Makefile')
Language.create(name: 'Mako')
Language.create(name: 'Markdown')
Language.create(name: 'Mask')
Language.create(name: 'Mathematica')
Language.create(name: 'Matlab')
Language.create(name: 'Maven POM')
Language.create(name: 'Max')
Language.create(name: 'MediaWiki')
Language.create(name: 'Mercury')
Language.create(name: 'Metal')
Language.create(name: 'MiniD')
Language.create(name: 'Mirah')
Language.create(name: 'Modelica')
Language.create(name: 'Modula-2')
Language.create(name: 'Module Management System')
Language.create(name: 'Monkey')
Language.create(name: 'Moocode')
Language.create(name: 'MoonScript')
Language.create(name: 'Myghty')
Language.create(name: 'NCL')
Language.create(name: 'NL')
Language.create(name: 'NSIS')
Language.create(name: 'Nemerle')
Language.create(name: 'NetLinx')
Language.create(name: 'NetLinx+ERB')
Language.create(name: 'NetLogo')
Language.create(name: 'NewLisp')
Language.create(name: 'Nginx')
Language.create(name: 'Nimrod')
Language.create(name: 'Ninja')
Language.create(name: 'Nit')
Language.create(name: 'Nix')
Language.create(name: 'Nu')
Language.create(name: 'NumPy')
Language.create(name: 'OCaml')
Language.create(name: 'ObjDump')
Language.create(name: 'Objective-C')
Language.create(name: 'Objective-C++')
Language.create(name: 'Objective-J')
Language.create(name: 'Omgrofl')
Language.create(name: 'Opa')
Language.create(name: 'Opal')
Language.create(name: 'OpenCL')
Language.create(name: 'OpenEdge ABL')
Language.create(name: 'OpenSCAD')
Language.create(name: 'Org')
Language.create(name: 'Ox')
Language.create(name: 'Oxygene')
Language.create(name: 'Oz')
Language.create(name: 'PAWN')
Language.create(name: 'PHP')
Language.create(name: 'Oracle')
Language.create(name: 'Postgres')
Language.create(name: 'Pan')
Language.create(name: 'Papyrus')
Language.create(name: 'Parrot')
Language.create(name: 'Parrot Assembly')
Language.create(name: 'Parrot Internal Representation')
Language.create(name: 'Pascal')
Language.create(name: 'Perl')
Language.create(name: 'Perl6')
Language.create(name: 'Pickle')
Language.create(name: 'PicoLisp')
Language.create(name: 'PigLatin')
Language.create(name: 'Pike')
Language.create(name: 'Pod')
Language.create(name: 'PogoScript')
Language.create(name: 'Pony')
Language.create(name: 'PostScript')
Language.create(name: 'PowerShell')
Language.create(name: 'Processing')
Language.create(name: 'Prolog')
Language.create(name: 'Propeller Spin')
Language.create(name: 'Protocol Buffer')
Language.create(name: 'Public Key')
Language.create(name: 'Puppet')
Language.create(name: 'Pure Data')
Language.create(name: 'PureBasic')
Language.create(name: 'PureScript')
Language.create(name: 'Python')
Language.create(name: 'Python traceback')
Language.create(name: 'QML')
Language.create(name: 'QMake')
Language.create(name: 'R')
Language.create(name: 'RAML')
Language.create(name: 'RDoc')
Language.create(name: 'REALbasic')
Language.create(name: 'RHTML')
Language.create(name: 'RMarkdown')
Language.create(name: 'Racket')
Language.create(name: 'Ragel in Ruby Host')
Language.create(name: 'Raw token data')
Language.create(name: 'Rebol')
Language.create(name: 'Red')
Language.create(name: 'Redcode')
Language.create(name: "Ren'Py")
Language.create(name: 'RenderScript')
Language.create(name: 'RobotFramework')
Language.create(name: 'Rouge')
Language.create(name: 'Ruby')
Language.create(name: 'Rust')
Language.create(name: 'SAS')
Language.create(name: 'SCSS')
Language.create(name: 'SMT')
Language.create(name: 'SPARQL')
Language.create(name: 'SQF')
Language.create(name: 'SQL')
Language.create(name: 'IBM DB2')
Language.create(name: 'STON')
Language.create(name: 'SVG')
Language.create(name: 'Sage')
Language.create(name: 'SaltStack')
Language.create(name: 'Sass')
Language.create(name: 'Scala')
Language.create(name: 'Scaml')
Language.create(name: 'Scheme')
Language.create(name: 'Scilab')
Language.create(name: 'Self')
Language.create(name: 'Shell')
Language.create(name: 'ShellSession')
Language.create(name: 'Shen')
Language.create(name: 'Slash')
Language.create(name: 'Slim')
Language.create(name: 'Smali')
Language.create(name: 'Smalltalk')
Language.create(name: 'Smarty')
Language.create(name: 'SourcePawn')
Language.create(name: 'Squirrel')
Language.create(name: 'Stan')
Language.create(name: 'Standard ML')
Language.create(name: 'Stata')
Language.create(name: 'Stylus')
Language.create(name: 'SuperCollider')
Language.create(name: 'Swift')
Language.create(name: 'SystemVerilog')
Language.create(name: 'TOML')
Language.create(name: 'TXL')
Language.create(name: 'Tcl')
Language.create(name: 'Tcsh')
Language.create(name: 'TeX')
Language.create(name: 'Tea')
Language.create(name: 'Text')
Language.create(name: 'Textile')
Language.create(name: 'Thrift')
Language.create(name: 'Turing')
Language.create(name: 'Turtle')
Language.create(name: 'Twig')
Language.create(name: 'TypeScript')
Language.create(name: 'Unified Parallel C')
Language.create(name: 'Unity3D Asset')
Language.create(name: 'UnrealScript')
Language.create(name: 'UrWeb')
Language.create(name: 'VCL')
Language.create(name: 'VHDL')
Language.create(name: 'Vala')
Language.create(name: 'Verilog')
Language.create(name: 'VimL')
Language.create(name: 'Visual Basic')
Language.create(name: 'Volt')
Language.create(name: 'Vue')
Language.create(name: 'Web Ontology Language')
Language.create(name: 'WebIDL')
Language.create(name: 'X10')
Language.create(name: 'XC')
Language.create(name: 'XML')
Language.create(name: 'XPages')
Language.create(name: 'XProc')
Language.create(name: 'XQuery')
Language.create(name: 'XS')
Language.create(name: 'XSLT')
Language.create(name: 'Xojo')
Language.create(name: 'Xtend')
Language.create(name: 'YAML')
Language.create(name: 'YANG')
Language.create(name: 'Yacc')
Language.create(name: 'Zephir')
Language.create(name: 'Zimpl')
Language.create(name: 'desktop')
Language.create(name: 'eC')
Language.create(name: 'edn')
Language.create(name: 'fish')
Language.create(name: 'mupad')
Language.create(name: 'nesC')
Language.create(name: 'ooc')
Language.create(name: 'reStructuredText')
Language.create(name: 'wisp')
Language.create(name: 'xBase')
